FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["RiseTechnology.Contact.API/RiseTechnology.Contact.API.csproj", "RiseTechnology.Contact.API/"]
RUN dotnet restore "RiseTechnology.Contact.API/RiseTechnology.Contact.API.csproj"
COPY . .
WORKDIR "/src/RiseTechnology.Contact.API"
RUN dotnet build "RiseTechnology.Contact.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "RiseTechnology.Contact.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RiseTechnology.Contact.API.dll"]